// Auto-generated by `tag build-css` — do not edit manually.

export const CDN_BASE = 'https://cdn.jsdelivr.net/gh/GaZmagik/text-adventure-games@v1.4.0/.claude/skills/text-adventure/assets';

export const CSS_MANIFEST: Record<string, string> = {
  'art-deco': '4776c1d8',
  'blueprint': '7a9873b7',
  'brutalist': 'f8e36cbf',
  'holographic': '0105e970',
  'ink-wash': 'd22ab7b4',
  'neon': 'e3082620',
  'parchment': '5c46dbe9',
  'stained-glass': '32d43420',
  'station': 'be0934b0',
  'sveltekit': 'a7379a18',
  'terminal': '78e22900',
  'weathered': 'a80746ec',
  'pregame-design': '662e4718',
  'scene-design': '7529a0b0',
  'common-widget': 'cd6535a0',
};

export const JS_MANIFEST: Record<string, string> = {
  'ta-components.js': '907f6c5c',
  'tag-scene.js': '3d31f2ec',
  'tag-soundscape.js': '6ec84062',
};

export const ICON_SPRITE_URL = `${CDN_BASE}/icons/sprite.svg?v=f0889e50`;
export const ICON_SPRITE_HASH = 'f0889e50';
