import { readdirSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { CommandResult } from '../types';
import { ok, fail } from '../lib/errors';
import { extractCssFromContent } from '../render/css-extractor';
import { fnv32 } from '../lib/fnv32';
import { SCENE_SCRIPT_CODE } from '../render/lib/scene-script';
import { SOUNDSCAPE_ENGINE_CODE } from '../render/lib/soundscape';
import { TA_COMPONENTS_CODE } from '../render/lib/ta-components';
import { PREGAME_DESIGN_CSS } from '../render/lib/pregame-design';
import { SCENE_DESIGN_CSS } from '../render/lib/scene-design';
import { COMMON_WIDGET_CSS } from '../render/lib/common-css';

const COMMAND = 'build-css';

// ── Paths ────────────────────────────────────────────────────────────

const CLI_DIR = resolve(import.meta.dir, '..');
const SKILL_DIR = resolve(CLI_DIR, '..');
const STYLES_DIR = join(SKILL_DIR, 'styles');
const DEFAULT_OUTPUT_DIR = join(SKILL_DIR, 'assets');
const ICONS_DIR = join(SKILL_DIR, 'icons');

const CDN_ASSET_PATH = '/.claude/skills/text-adventure/assets';

/** Detect the current HEAD commit for an immutable CDN ref. Falls back to 'main'. */
function detectGitRef(): string {
  try {
    const result = Bun.spawnSync(['git', 'rev-parse', '--short', 'HEAD']);
    const commit = result.stdout.toString().trim();
    return commit || 'main';
  } catch {
    return 'main';
  }
}

function buildCdnBase(ref: string, user: string): string {
  // Encode the git ref conservatively so tags/branches like feature/foo
  // are emitted as a single ref token rather than a path segment.
  const safeRef = encodeURIComponent(ref);
  return `https://cdn.jsdelivr.net/gh/${user}/text-adventure-games@${safeRef}${CDN_ASSET_PATH}`;
}

// ── Minification ─────────────────────────────────────────────────────

/** Simple CSS minification: strip comments, collapse whitespace. */
function minifyCss(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')   // strip comments
    .replace(/\s*\n\s*/g, '\n')         // collapse line whitespace
    .replace(/\n{2,}/g, '\n')           // collapse blank lines
    .trim();
}

// ── Style entry type ─────────────────────────────────────────────────

type StyleEntry = {
  name: string;
  hash: string;
  bytes: number;
  path: string;
};

type ScriptEntry = {
  fileName: string;
  hash: string;
  bytes: number;
  path: string;
};

// ── Parse args ───────────────────────────────────────────────────────

function parseArgs(args: string[]): { outputDir: string; release: string | null; user: string } {
  let outputDir = DEFAULT_OUTPUT_DIR;
  let release: string | null = null;
  let user = 'GaZmagik';
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output-dir' && args[i + 1]) {
      outputDir = resolve(args[i + 1]!);
      i++;
    } else if (args[i] === '--release' && args[i + 1]) {
      release = args[i + 1]!;
      i++;
    } else if (args[i] === '--user' && args[i + 1]) {
      user = args[i + 1]!;
      i++;
    }
  }
  return { outputDir, release, user };
}

// ── Manifest generation ──────────────────────────────────────────────

function generateManifest(entries: StyleEntry[], scripts: ScriptEntry[], cdnBase: string, spriteHash?: string): string {
  const lines: string[] = [
    `// Auto-generated by \`tag build-css\` — do not edit manually.`,
    ``,
    `export const CDN_BASE = '${cdnBase}';`,
    ``,
    `export const CSS_MANIFEST: Record<string, string> = {`,
  ];
  for (const entry of entries) {
    lines.push(`  '${entry.name}': '${entry.hash}',`);
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(`export const JS_MANIFEST: Record<string, string> = {`);
  for (const script of scripts) {
    lines.push(`  '${script.fileName}': '${script.hash}',`);
  }
  lines.push(`};`);
  lines.push(``);
  if (spriteHash) {
    lines.push(`export const ICON_SPRITE_URL = \`\${CDN_BASE}/icons/sprite.svg?v=${spriteHash}\`;`);
    lines.push(`export const ICON_SPRITE_HASH = '${spriteHash}';`);
    lines.push(``);
  }
  return lines.join('\n');
}

// ── Main handler ─────────────────────────────────────────────────────

export async function handleBuildCss(args: string[]): Promise<CommandResult> {
  const { outputDir, release, user } = parseArgs(args);
  const ref = release ?? detectGitRef();
  const cdnBase = buildCdnBase(ref, user);

  // Discover style files (exclude style-reference.md)
  let styleFiles: string[];
  try {
    styleFiles = readdirSync(STYLES_DIR)
      .filter(f => f.endsWith('.md') && f !== 'style-reference.md')
      .sort();
  } catch {
    return fail(
      `Cannot read styles directory: ${STYLES_DIR}`,
      'Ensure the styles/ directory exists alongside the cli/ directory.',
      COMMAND,
    );
  }

  if (styleFiles.length === 0) {
    return fail(
      'No style files found in styles/ directory.',
      'Add .md style files to the styles/ directory.',
      COMMAND,
    );
  }

  // Read style-reference.md for shared structural CSS
  const refPath = join(STYLES_DIR, 'style-reference.md');
  const refFile = Bun.file(refPath);
  let referenceCss = '';
  if (await refFile.exists()) {
    const refContent = await refFile.text();
    referenceCss = extractCssFromContent(refContent);
  }

  // Ensure output directories exist
  const cssDir = join(outputDir, 'css');
  const jsDir = join(outputDir, 'js');
  mkdirSync(cssDir, { recursive: true });
  mkdirSync(jsDir, { recursive: true });

  // Process each style file
  const entries: StyleEntry[] = [];
  const scripts: ScriptEntry[] = [];
  let totalBytes = 0;

  for (const file of styleFiles) {
    const name = file.replace(/\.md$/, '');
    const filePath = join(STYLES_DIR, file);
    const content = await Bun.file(filePath).text();

    // Extract CSS from the style file (no scope filter)
    const styleCss = extractCssFromContent(content);

    // Combine: style-specific CSS first, then reference CSS
    const combined = [styleCss, referenceCss].filter(Boolean).join('\n\n');

    // Minify
    const minified = minifyCss(combined);

    // Compute hash
    const hash = fnv32(minified);

    // Write output file
    const outPath = join(cssDir, `${name}.css`);
    await Bun.write(outPath, minified);

    const bytes = Buffer.byteLength(minified, 'utf-8');
    totalBytes += bytes;

    entries.push({ name, hash, bytes, path: outPath });
  }

  // Write the structural CSS files
  const structuralCss = [
    { name: 'pregame-design', content: PREGAME_DESIGN_CSS },
    { name: 'scene-design', content: SCENE_DESIGN_CSS },
    { name: 'common-widget', content: COMMON_WIDGET_CSS }
  ];

  for (const style of structuralCss) {
    const minified = minifyCss(style.content);
    const hash = fnv32(minified);
    const outPath = join(cssDir, `${style.name}.css`);
    await Bun.write(outPath, minified);
    const bytes = Buffer.byteLength(minified, 'utf-8');
    totalBytes += bytes;
    entries.push({ name: style.name, hash, bytes, path: outPath });
  }

  const scriptAssets = [
    {
      fileName: 'ta-components.js',
      sourcePath: 'cli/render/lib/ta-components.ts',
      content: `${TA_COMPONENTS_CODE}\n`,
    },
    {
      fileName: 'tag-scene.js',
      sourcePath: 'cli/render/lib/scene-script.ts',
      content: `${SCENE_SCRIPT_CODE}\n`,
    },
    {
      fileName: 'tag-soundscape.js',
      sourcePath: 'cli/render/lib/soundscape.ts',
      content: `${SOUNDSCAPE_ENGINE_CODE}\n`,
    },
  ];

  for (const asset of scriptAssets) {
    const fileContent = [
      `// Auto-generated by \`tag build-css\` from ${asset.sourcePath} — do not edit manually.`,
      '',
      asset.content.trim(),
      '',
    ].join('\n');
    const outPath = join(jsDir, asset.fileName);
    await Bun.write(outPath, fileContent);
    const bytes = Buffer.byteLength(fileContent, 'utf-8');
    totalBytes += bytes;
    scripts.push({
      fileName: asset.fileName,
      hash: fnv32(fileContent),
      bytes,
      path: outPath,
    });
  }

  // ── SVG Sprite generation ───────────────────────────────────────────
  const iconsDir = join(outputDir, 'icons');
  mkdirSync(iconsDir, { recursive: true });
  
  let spriteHash: string | undefined;
  try {
    const iconFiles = readdirSync(ICONS_DIR).filter(f => f.endsWith('.svg')).sort();
    if (iconFiles.length > 0) {
      const symbols: string[] = [];
      for (const file of iconFiles) {
        const id = file.replace(/\.svg$/, '');
        if (!/^[a-z0-9_-]+$/i.test(id)) continue;
        const content = await Bun.file(join(ICONS_DIR, file)).text();
        // Simple extraction of path/shapes from SVG, assuming they are clean
        const inner = content
          .replace(/<svg[^>]*>/i, '')
          .replace(/<\/svg>/i, '')
          .trim();
        symbols.push(`<symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`);
      }
      const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${symbols.join('')}</svg>`;
      spriteHash = fnv32(sprite);
      await Bun.write(join(iconsDir, 'sprite.svg'), sprite);
    }
  } catch (e) {
    // Icons dir might not exist or read failed, skip silently
  }

  // Generate CDN manifest
  const manifest = generateManifest(entries, scripts, cdnBase, spriteHash);
  const manifestPath = join(outputDir, 'cdn-manifest.ts');
  await Bun.write(manifestPath, manifest);

  return ok(
    {
      styles: entries,
      scripts,
      totalBytes,
      manifestPath,
      outputDir,
    },
    COMMAND,
  );
}
