import { readdirSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { CommandResult } from '../types';
import { ok, fail } from '../lib/errors';
import { extractCssFromContent } from '../render/css-extractor';
import { fnv32 } from '../lib/fnv32';

const COMMAND = 'build-css';

// ── Paths ────────────────────────────────────────────────────────────

const CLI_DIR = resolve(import.meta.dir, '..');
const SKILL_DIR = resolve(CLI_DIR, '..');
const STYLES_DIR = join(SKILL_DIR, 'styles');
const DEFAULT_OUTPUT_DIR = join(SKILL_DIR, 'assets');

const CDN_BASE = 'https://cdn.jsdelivr.net/gh/GaZmagik/text-adventure-games@main/.claude/skills/text-adventure/assets';

// ── Minification ─────────────────────────────────────────────────────

/** Simple CSS minification: strip comments, collapse whitespace. */
function minifyCss(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')   // strip comments
    .replace(/\s*\n\s*/g, '\n')         // collapse line whitespace
    .replace(/\n{2,}/g, '\n')           // collapse blank lines
    .trim();
}

// ── Style entry type ─────────────────────────────────────────────────

type StyleEntry = {
  name: string;
  hash: string;
  bytes: number;
  path: string;
};

// ── Parse args ───────────────────────────────────────────────────────

function parseArgs(args: string[]): { outputDir: string } {
  let outputDir = DEFAULT_OUTPUT_DIR;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output-dir' && args[i + 1]) {
      outputDir = resolve(args[i + 1]!);
      i++;
    }
  }
  return { outputDir };
}

// ── Manifest generation ──────────────────────────────────────────────

function generateManifest(entries: StyleEntry[]): string {
  const lines: string[] = [
    `// Auto-generated by \`tag build-css\` — do not edit manually.`,
    ``,
    `export const CDN_BASE = '${CDN_BASE}';`,
    ``,
    `export const CSS_MANIFEST: Record<string, string> = {`,
  ];
  for (const entry of entries) {
    lines.push(`  '${entry.name}': '${entry.hash}',`);
  }
  lines.push(`};`);
  lines.push(``);
  return lines.join('\n');
}

// ── Main handler ─────────────────────────────────────────────────────

export async function handleBuildCss(args: string[]): Promise<CommandResult> {
  const { outputDir } = parseArgs(args);

  // Discover style files (exclude style-reference.md)
  let styleFiles: string[];
  try {
    styleFiles = readdirSync(STYLES_DIR)
      .filter(f => f.endsWith('.md') && f !== 'style-reference.md')
      .sort();
  } catch {
    return fail(
      `Cannot read styles directory: ${STYLES_DIR}`,
      'Ensure the styles/ directory exists alongside the cli/ directory.',
      COMMAND,
    );
  }

  if (styleFiles.length === 0) {
    return fail(
      'No style files found in styles/ directory.',
      'Add .md style files to the styles/ directory.',
      COMMAND,
    );
  }

  // Read style-reference.md for shared structural CSS
  const refPath = join(STYLES_DIR, 'style-reference.md');
  const refFile = Bun.file(refPath);
  let referenceCss = '';
  if (await refFile.exists()) {
    const refContent = await refFile.text();
    referenceCss = extractCssFromContent(refContent);
  }

  // Ensure output directories exist
  const cssDir = join(outputDir, 'css');
  mkdirSync(cssDir, { recursive: true });

  // Process each style file
  const entries: StyleEntry[] = [];
  let totalBytes = 0;

  for (const file of styleFiles) {
    const name = file.replace(/\.md$/, '');
    const filePath = join(STYLES_DIR, file);
    const content = await Bun.file(filePath).text();

    // Extract CSS from the style file (no scope filter)
    const styleCss = extractCssFromContent(content);

    // Combine: style-specific CSS first, then reference CSS
    const combined = [styleCss, referenceCss].filter(Boolean).join('\n\n');

    // Minify
    const minified = minifyCss(combined);

    // Compute hash
    const hash = fnv32(minified);

    // Write output file
    const outPath = join(cssDir, `${name}.css`);
    await Bun.write(outPath, minified);

    const bytes = Buffer.byteLength(minified, 'utf-8');
    totalBytes += bytes;

    entries.push({ name, hash, bytes, path: outPath });
  }

  // Generate CDN manifest
  const manifest = generateManifest(entries);
  const manifestPath = join(outputDir, 'cdn-manifest.ts');
  await Bun.write(manifestPath, manifest);

  return ok(
    {
      styles: entries,
      totalBytes,
      manifestPath,
      outputDir,
    },
    COMMAND,
  );
}
